// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Info summarizes a workflow for the list view. Installed marks a per-bot entry
 * that is a symlink into the marketplace catalog (vs. a real per-bot script).
 * Broken marks an installed symlink whose catalog target no longer resolves
 * (e.g. the marketplace entry was deleted) — surfaced so the UI can offer to
 * uninstall the orphan.
 */
export class Info {
    "name": string;
    "description": string;
    "installed": boolean;
    "broken": boolean;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("broken" in $$source)) {
            this["broken"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info($$parsedSource as Partial<Info>);
    }
}
